// Code generated by server_generator. DO NOT EDIT.
// generated version: devel

package users

import (
	"io"
	"log"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/rhyth-me/backend/api/apigen/props"
	"github.com/rhyth-me/backend/api/apigen/wrapper"
	"golang.org/x/xerrors"
)

// Routes ...
type Routes struct {
	router *echo.Group
}

// NewRoutes ...
func NewRoutes(p *props.ControllerProps, router *echo.Group, opts ...io.Writer) *Routes {
	if len(opts) > 0 {
		if w := opts[0]; w != nil {
			log.SetOutput(w)
		}
	}
	r := &Routes{
		router: router,
	}
	router.GET("items", r.GetItems(p))
	router.GET("summary", r.GetSummary(p))
	return r
}

// GetItems ...
func (r *Routes) GetItems(p *props.ControllerProps) echo.HandlerFunc {
	i := NewGetItemsController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *GetItemsRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(GetItemsRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/_userID/items): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.GetItems(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// GetSummary ...
func (r *Routes) GetSummary(p *props.ControllerProps) echo.HandlerFunc {
	i := NewGetSummaryController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *GetSummaryRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(GetSummaryRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/_userID/summary): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.GetSummary(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// IGetItemsController ...
type IGetItemsController interface {
	GetItems(c echo.Context, req *GetItemsRequest) (res *GetItemsResponse, err error)
}

// IGetSummaryController ...
type IGetSummaryController interface {
	GetSummary(c echo.Context, req *GetSummaryRequest) (res *GetSummaryResponse, err error)
}
