// Code generated by server_generator. DO NOT EDIT.
// generated version: 1.8.0

package accounts

import (
	"io"
	"log"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/rhyth-me/backend/interfaces/props"
	"github.com/rhyth-me/backend/interfaces/wrapper"
	"golang.org/x/xerrors"
)

// Routes ...
type Routes struct {
	router *echo.Group
}

// NewRoutes ...
func NewRoutes(p *props.ControllerProps, router *echo.Group, opts ...io.Writer) *Routes {
	if len(opts) > 0 {
		if w := opts[0]; w != nil {
			log.SetOutput(w)
		}
	}
	r := &Routes{
		router: router,
	}
	router.POST("stripe", r.PostStripe(p))
	return r
}

// PostStripe ...
func (r *Routes) PostStripe(p *props.ControllerProps) echo.HandlerFunc {
	i := NewPostStripeController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *PostStripeRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(PostStripeRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/_userID/accounts/stripe): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.PostStripe(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// IPostStripeController ...
type IPostStripeController interface {
	PostStripe(c echo.Context, req *PostStripeRequest) (res *PostStripeResponse, err error)
}
