// Code generated by server_generator. DO NOT EDIT.
// generated version: devel

package account

import (
	"io"
	"log"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/rhyth-me/backend/api/apigen/props"
	"github.com/rhyth-me/backend/api/apigen/wrapper"
	"golang.org/x/xerrors"
)

// Routes ...
type Routes struct {
	router *echo.Group
}

// NewRoutes ...
func NewRoutes(p *props.ControllerProps, router *echo.Group, opts ...io.Writer) *Routes {
	if len(opts) > 0 {
		if w := opts[0]; w != nil {
			log.SetOutput(w)
		}
	}
	r := &Routes{
		router: router,
	}
	router.GET("profile", r.GetProfile(p))
	router.PUT("cards", r.PutCards(p))
	router.PUT("profile", r.PutProfile(p))
	return r
}

// GetProfile ...
func (r *Routes) GetProfile(p *props.ControllerProps) echo.HandlerFunc {
	i := NewGetProfileController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *GetProfileRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(GetProfileRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/profile): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.GetProfile(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// PutCards ...
func (r *Routes) PutCards(p *props.ControllerProps) echo.HandlerFunc {
	i := NewPutCardsController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *PutCardsRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(PutCardsRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/cards): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.PutCards(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// PutProfile ...
func (r *Routes) PutProfile(p *props.ControllerProps) echo.HandlerFunc {
	i := NewPutProfileController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *PutProfileRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(PutProfileRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/profile): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.PutProfile(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// IGetProfileController ...
type IGetProfileController interface {
	GetProfile(c echo.Context, req *GetProfileRequest) (res *GetProfileResponse, err error)
}

// IPutCardsController ...
type IPutCardsController interface {
	PutCards(c echo.Context, req *PutCardsRequest) (res *PutCardsResponse, err error)
}

// IPutProfileController ...
type IPutProfileController interface {
	PutProfile(c echo.Context, req *PutProfileRequest) (res *PutProfileResponse, err error)
}
