// Code generated by server_generator. DO NOT EDIT.
// generated version: devel

package account

import (
	"io"
	"log"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/rhyth-me/backend/api/apigen/props"
	"github.com/rhyth-me/backend/api/apigen/wrapper"
	"golang.org/x/xerrors"
)

// Routes ...
type Routes struct {
	router *echo.Group
}

// NewRoutes ...
func NewRoutes(p *props.ControllerProps, router *echo.Group, opts ...io.Writer) *Routes {
	if len(opts) > 0 {
		if w := opts[0]; w != nil {
			log.SetOutput(w)
		}
	}
	r := &Routes{
		router: router,
	}
	router.DELETE("cards", r.DeleteCards(p))
	router.GET("cards", r.GetCards(p))
	router.GET("connect", r.GetConnect(p))
	router.GET("profile", r.GetProfile(p))
	router.PATCH("profile", r.PatchProfile(p))
	router.PUT("cards", r.PutCards(p))
	router.PUT("connect", r.PutConnect(p))
	return r
}

// DeleteCards ...
func (r *Routes) DeleteCards(p *props.ControllerProps) echo.HandlerFunc {
	i := NewDeleteCardsController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *DeleteCardsRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(DeleteCardsRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/cards): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.DeleteCards(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// GetCards ...
func (r *Routes) GetCards(p *props.ControllerProps) echo.HandlerFunc {
	i := NewGetCardsController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *GetCardsRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(GetCardsRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/cards): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.GetCards(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// GetConnect ...
func (r *Routes) GetConnect(p *props.ControllerProps) echo.HandlerFunc {
	i := NewGetConnectController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *GetConnectRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(GetConnectRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/connect): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.GetConnect(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// GetProfile ...
func (r *Routes) GetProfile(p *props.ControllerProps) echo.HandlerFunc {
	i := NewGetProfileController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *GetProfileRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(GetProfileRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/profile): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.GetProfile(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// PatchProfile ...
func (r *Routes) PatchProfile(p *props.ControllerProps) echo.HandlerFunc {
	i := NewPatchProfileController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *PatchProfileRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(PatchProfileRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/profile): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.PatchProfile(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// PutCards ...
func (r *Routes) PutCards(p *props.ControllerProps) echo.HandlerFunc {
	i := NewPutCardsController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *PutCardsRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(PutCardsRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/cards): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.PutCards(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// PutConnect ...
func (r *Routes) PutConnect(p *props.ControllerProps) echo.HandlerFunc {
	i := NewPutConnectController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var (
			req  *PutConnectRequest
			werr *wrapper.APIError
		)

		if bindable {
			req = new(PutConnectRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/account/connect): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				if xerrors.As(err, &werr) {
					return c.JSON(werr.Status, werr.Body)
				}
				return err
			}
		}
		res, err := i.PutConnect(c, req)
		if err != nil {
			if xerrors.As(err, &werr) {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// IDeleteCardsController ...
type IDeleteCardsController interface {
	DeleteCards(c echo.Context, req *DeleteCardsRequest) (res *DeleteCardsResponse, err error)
}

// IGetCardsController ...
type IGetCardsController interface {
	GetCards(c echo.Context, req *GetCardsRequest) (res *GetCardsResponse, err error)
}

// IGetConnectController ...
type IGetConnectController interface {
	GetConnect(c echo.Context, req *GetConnectRequest) (res *GetConnectResponse, err error)
}

// IGetProfileController ...
type IGetProfileController interface {
	GetProfile(c echo.Context, req *GetProfileRequest) (res *GetProfileResponse, err error)
}

// IPatchProfileController ...
type IPatchProfileController interface {
	PatchProfile(c echo.Context, req *PatchProfileRequest) (res *PatchProfileResponse, err error)
}

// IPutCardsController ...
type IPutCardsController interface {
	PutCards(c echo.Context, req *PutCardsRequest) (res *PutCardsResponse, err error)
}

// IPutConnectController ...
type IPutConnectController interface {
	PutConnect(c echo.Context, req *PutConnectRequest) (res *PutConnectResponse, err error)
}
